<?php

namespace common\models;

use common\models\base\InventoryBase;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

class Inventory extends InventoryBase
{
    public function behaviors()
    {
        return [
            [
                'class'              => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'modified_by',
            ],
            [
                'class'              => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_date',
                'updatedAtAttribute' => 'modified_date',
                'value'              => strtotime(date('d.m.Y H:i:s')),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'stay_date_from'        => 'Ngày ở từ',
            'stay_date_to'        => 'Ngày ở đến',
            'sold_date'        => 'Ngày bán',
            'inventory_status' => 'Inventory Status',
            'note'             => 'Note',
            'sold_date_from'   => 'Ngày bán từ',
            'sold_date_to'     => 'Ngày bán đến',
            'status'           => 'Trạng thái',
            'order_code'       => 'Mã đơn hàng',
            'customer_name'    => 'Tên khách hàng',
            'customer_phone'   => 'Số điện thoại',
            'customer_email'   => 'Email',
            'voucher'          => 'Mã voucher',
            'quantity'         => 'Tổng số lượng',
            'in_stock'         => 'Tổng số còn',
            'waiting'          => 'Tổng số chờ thanh toán',
            'sold'             => 'Tổng số đã bán',
        ];
    }

    //	public function beforeSave( $insert ) {
    //		if ( parent::beforeSave( $insert ) ) {
    //			if ( $insert ) {
    //				//nếu là thêm mới
    //			}
    //
    //			return true;
    //		} else {
    //			return false;
    //		}
    //	}

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        $rooms = Inventory::find()->where(['status' => 1])
                          ->groupBy(['stay_date'])->select('stay_date, count(*) as quantity')
                          ->createCommand()->queryAll();
        Yii::$app->cache->set('rooms', $rooms);
    }

    public function getStatus()
    {
        if ($this->status > 0) {
            if ($this->inventory_status == 0) {
                return 'Còn';
            }
            if ($this->inventory_status == 2) {
                return 'Chờ thanh toán';
            }
            if ($this->inventory_status == 3) {
                return 'Chờ xác nhận';
            }

            return 'Đã bán';
        }

        return 'Khóa';
    }
}
